// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proj_ICFT.DataNew;

#nullable disable

namespace Proj_ICFT.Migrations
{
    [DbContext(typeof(AppDbContextNew))]
    [Migration("20260530195323_AddEvolucaoClinica")]
    partial class AddEvolucaoClinica
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Blocos_CID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChapterNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Grouping1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Grouping2")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleEN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Blocks__3214EC07C8C74789");

                    b.HasIndex("ChapterNo");

                    b.HasIndex(new[] { "BlockId" }, "UQ_Blocks_BlockId")
                        .IsUnique()
                        .HasFilter("[BlockId] IS NOT NULL");

                    b.ToTable("Blocos_CID");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Capitulos_CID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FoundationURI")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LinearizationURI")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleEN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Chapters__3214EC0741E1B9B3");

                    b.HasIndex(new[] { "ChapterNo" }, "UQ_Chapters_ChapterNo")
                        .IsUnique();

                    b.ToTable("Capitulos_CID");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Categorias_CID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ChapterNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool?>("IsLeaf")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TitleEN")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC0775CEAE9D");

                    b.HasIndex("ChapterNo");

                    b.ToTable("Categorias_CID");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Categorium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.EvolucaoClinica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Avaliacao")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("CategoriaCID_ID")
                        .HasColumnType("int");

                    b.Property<double?>("Creatinina")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<int>("EventosAdversos")
                        .HasColumnType("int");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("int");

                    b.Property<double?>("Glicemia")
                        .HasColumnType("float");

                    b.Property<double?>("Hba1c")
                        .HasColumnType("float");

                    b.Property<int>("Hospitalizacoes")
                        .HasColumnType("int");

                    b.Property<int>("IdasEmergencia")
                        .HasColumnType("int");

                    b.Property<string>("ObservacaoObjetivo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("PaDiastolica")
                        .HasColumnType("int");

                    b.Property<int?>("PaSistolica")
                        .HasColumnType("int");

                    b.Property<int>("PacienteID")
                        .HasColumnType("int");

                    b.Property<double?>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("Plano")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ReceitaID")
                        .HasColumnType("int");

                    b.Property<int?>("Spo2")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subjetivo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UsuarioCriacaoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaCID_ID");

                    b.HasIndex("PacienteID")
                        .HasDatabaseName("IX_EvolucaoClinica_PacienteID");

                    b.HasIndex("ReceitaID");

                    b.HasIndex("UsuarioCriacaoID");

                    b.HasIndex("PacienteID", "DataConsulta")
                        .HasDatabaseName("IX_EvolucaoClinica_Paciente_Data");

                    b.ToTable("EvolucaoClinica");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Frequencium", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Frequencia");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.InstrucoesAdicionai", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("InstrucoesAdicionais");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.InstrucoesMed", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("InstrucaoId")
                        .HasColumnType("int");

                    b.Property<int>("Med_ReceitaID")
                        .HasColumnType("int");

                    b.HasKey("id")
                        .HasName("PK_InstrucoesAdicionais_Paciente");

                    b.HasIndex("InstrucaoId");

                    b.HasIndex("Med_ReceitaID");

                    b.ToTable("InstrucoesMed");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CATEGORIA_REGULATORIA")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CLASSE_TERAPEUTICA")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EMPRESA_DETENTORA_REGISTRO")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NOME_PRODUTO")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NUMERO_REGISTRO_PRODUTO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PRINCIPIO_ATIVO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SITUACAO_REGISTRO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Medicame__3214EC079B86793D");

                    b.ToTable("Medicamentos");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.PacienteICT", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<int>("UsuarioCriacaoID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioCriacaoID");

                    b.ToTable("PacienteICT");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.ReceitaCID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaCID_ID")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaID")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Categoria_CID_Receita");

                    b.HasIndex("CategoriaCID_ID");

                    b.HasIndex("ReceitaID");

                    b.ToTable("ReceitaCID");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.ReceitaMed", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoriaID")
                        .HasColumnType("int");

                    b.Property<int>("FrequenciaID")
                        .HasColumnType("int");

                    b.Property<int>("MedicamentoID")
                        .HasColumnType("int");

                    b.Property<int>("ReceitaID")
                        .HasColumnType("int");

                    b.Property<int>("TipoID")
                        .HasColumnType("int");

                    b.HasKey("ID")
                        .HasName("PK_Remedio_Paciente");

                    b.HasIndex("CategoriaID");

                    b.HasIndex("FrequenciaID");

                    b.HasIndex("MedicamentoID");

                    b.HasIndex("ReceitaID");

                    b.HasIndex("TipoID");

                    b.ToTable("ReceitaMed");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Receitum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Adesao")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<double>("ICT")
                        .HasColumnType("float");

                    b.Property<int>("PacienteID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCriacaoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PacienteID");

                    b.HasIndex("UsuarioCriacaoID");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Tipo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tipo");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Usuario1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Usuario");

                    b.HasKey("id");

                    b.HasIndex(new[] { "Usuario1" }, "IX_Usuarios")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Blocos_CID", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Capitulos_CID", "ChapterNoNavigation")
                        .WithMany("Blocos_CIDs")
                        .HasForeignKey("ChapterNo")
                        .HasPrincipalKey("ChapterNo")
                        .HasConstraintName("FK_Blocos_CID_Capitulos_CID");

                    b.Navigation("ChapterNoNavigation");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Categorias_CID", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Capitulos_CID", "ChapterNoNavigation")
                        .WithMany("Categorias_CIDs")
                        .HasForeignKey("ChapterNo")
                        .HasPrincipalKey("ChapterNo")
                        .IsRequired()
                        .HasConstraintName("FK_Categorias_CID_Capitulos_CID");

                    b.Navigation("ChapterNoNavigation");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.EvolucaoClinica", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Categorias_CID", "CategoriaCID")
                        .WithMany("EvolucaoClinicas")
                        .HasForeignKey("CategoriaCID_ID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_EvolucaoClinica_Categorias_CID");

                    b.HasOne("Proj_ICFT.ModelsNew.PacienteICT", "Paciente")
                        .WithMany("EvolucaoClinicas")
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EvolucaoClinica_PacienteICT");

                    b.HasOne("Proj_ICFT.ModelsNew.Receitum", "Receita")
                        .WithMany("EvolucaoClinicas")
                        .HasForeignKey("ReceitaID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_EvolucaoClinica_Receita");

                    b.HasOne("Proj_ICFT.ModelsNew.Usuario", "UsuarioCriacao")
                        .WithMany("EvolucaoClinicas")
                        .HasForeignKey("UsuarioCriacaoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EvolucaoClinica_Usuario");

                    b.Navigation("CategoriaCID");

                    b.Navigation("Paciente");

                    b.Navigation("Receita");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.InstrucoesMed", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.InstrucoesAdicionai", "Instrucao")
                        .WithMany("InstrucoesMeds")
                        .HasForeignKey("InstrucaoId")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Instrucoes_InstrucoesAdicionais");

                    b.HasOne("Proj_ICFT.ModelsNew.ReceitaMed", "Med_Receita")
                        .WithMany("InstrucoesMeds")
                        .HasForeignKey("Med_ReceitaID")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Instrucoes_Med_Receita");

                    b.Navigation("Instrucao");

                    b.Navigation("Med_Receita");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.PacienteICT", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Usuario", "UsuarioCriacao")
                        .WithMany("PacienteICTs")
                        .HasForeignKey("UsuarioCriacaoID")
                        .IsRequired()
                        .HasConstraintName("FK_PacienteICT_Usuarios");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.ReceitaCID", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Categorias_CID", "CategoriaCID")
                        .WithMany("ReceitaCIDs")
                        .HasForeignKey("CategoriaCID_ID")
                        .IsRequired()
                        .HasConstraintName("FK_CID_Receita_Categorias_CID");

                    b.HasOne("Proj_ICFT.ModelsNew.Receitum", "Receita")
                        .WithMany("ReceitaCIDs")
                        .HasForeignKey("ReceitaID")
                        .IsRequired()
                        .HasConstraintName("FK_CID_Receita_Receita");

                    b.Navigation("CategoriaCID");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.ReceitaMed", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Categorium", "Categoria")
                        .WithMany("ReceitaMeds")
                        .HasForeignKey("CategoriaID")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Receita_Categoria");

                    b.HasOne("Proj_ICFT.ModelsNew.Frequencium", "Frequencia")
                        .WithMany("ReceitaMeds")
                        .HasForeignKey("FrequenciaID")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Receita_Frequencia");

                    b.HasOne("Proj_ICFT.ModelsNew.Medicamento", "Medicamento")
                        .WithMany("ReceitaMeds")
                        .HasForeignKey("MedicamentoID")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Receita_Medicamentos");

                    b.HasOne("Proj_ICFT.ModelsNew.Receitum", "Receita")
                        .WithMany("ReceitaMeds")
                        .HasForeignKey("ReceitaID")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Receita_Receita");

                    b.HasOne("Proj_ICFT.ModelsNew.Tipo", "Tipo")
                        .WithMany("ReceitaMeds")
                        .HasForeignKey("TipoID")
                        .IsRequired()
                        .HasConstraintName("FK_Med_Receita_Tipo");

                    b.Navigation("Categoria");

                    b.Navigation("Frequencia");

                    b.Navigation("Medicamento");

                    b.Navigation("Receita");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Receitum", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.PacienteICT", "Paciente")
                        .WithMany("Receita")
                        .HasForeignKey("PacienteID")
                        .IsRequired()
                        .HasConstraintName("FK_Receita_PacienteICT");

                    b.HasOne("Proj_ICFT.ModelsNew.Usuario", "UsuarioCriacao")
                        .WithMany("Receita")
                        .HasForeignKey("UsuarioCriacaoID")
                        .IsRequired()
                        .HasConstraintName("FK_Receita_Usuarios");

                    b.Navigation("Paciente");

                    b.Navigation("UsuarioCriacao");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Tipo", b =>
                {
                    b.HasOne("Proj_ICFT.ModelsNew.Categorium", "Categoria")
                        .WithMany("Tipos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK_Tipo_Categoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Capitulos_CID", b =>
                {
                    b.Navigation("Blocos_CIDs");

                    b.Navigation("Categorias_CIDs");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Categorias_CID", b =>
                {
                    b.Navigation("EvolucaoClinicas");

                    b.Navigation("ReceitaCIDs");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Categorium", b =>
                {
                    b.Navigation("ReceitaMeds");

                    b.Navigation("Tipos");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Frequencium", b =>
                {
                    b.Navigation("ReceitaMeds");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.InstrucoesAdicionai", b =>
                {
                    b.Navigation("InstrucoesMeds");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Medicamento", b =>
                {
                    b.Navigation("ReceitaMeds");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.PacienteICT", b =>
                {
                    b.Navigation("EvolucaoClinicas");

                    b.Navigation("Receita");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.ReceitaMed", b =>
                {
                    b.Navigation("InstrucoesMeds");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Receitum", b =>
                {
                    b.Navigation("EvolucaoClinicas");

                    b.Navigation("ReceitaCIDs");

                    b.Navigation("ReceitaMeds");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Tipo", b =>
                {
                    b.Navigation("ReceitaMeds");
                });

            modelBuilder.Entity("Proj_ICFT.ModelsNew.Usuario", b =>
                {
                    b.Navigation("EvolucaoClinicas");

                    b.Navigation("PacienteICTs");

                    b.Navigation("Receita");
                });
#pragma warning restore 612, 618
        }
    }
}
